version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: " somewppassword"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"

  wordpress:
    ports:
      - "${PORT:-8000}:80"
    depends_on: 
      - db
    image: wordpress:latest
    volumes: 
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: "db"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress"
      WORDPRESS_DB_NAME: "wordpress"

volumes:
  db_data: {}
  wordpress_data: {}